enum TokenType {

    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_BRACE, RIGHT_BRACE,
    COMMA, SEMICOLON, DOT, MINUS, PLUS, SLASH, STAR,

    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    IDENTIFIER, STRING, NUMBER,

    AND, CLASS, SUPER, ELSE, IF, FUN, FOR, WHILE, NIL, OR,
    PRINT, RETURN, THIS, TRUE, FALSE, VAR,

    EOF

}
